### PR TITLE
localization: Update to the wording of V4.0.8

### PR DESCRIPTION
**Pull request by muramura**
---
name: Bug report
about: Create a report to help us improve

---

**Describe the bug**
A clear and concise description of the bug.

The location of the text is inconsistent.
The number of sentences is different.

**To Reproduce**

Perform lupdate on QT.

**Expected behavior**

If your language is not English, it will be displayed in English.
and the text cannot be converted to the language of each country.

**Log Files and Screenshots**
*Always* add screenshots and the QGC console log.

None

**Drone (please complete the following information):**
- Describe the type of drone.
- Photo of the IMU / autopilot setup if possible.

HERELINK

**Additional context**
Add any other context about the problem here

### CODE REVIEW

**Comment by muramura** [comment]
I have supported the Japanese display.

**Comment by meee1** [comment]
im concerned about the size of this change, and it affecting every language.

**Comment by muramura** [comment]
If you change the source, the line of text will also change.
I use QT's LINGUIST tool for language conversion.
When I use this tool to do a language conversion, I want it to match the line of text.

I would like to add Japanese support to HERELINK.
I have already done all the Japanese support.
I am working on Japanese support based on this PR.

LINGUIST tool
Screenshot from 2021-09-22 07-19-41

**Comment by muramura** [comment]
@meee1 san.
I will only promote the Japanese files.

**Comment by muramura** [comment]
This PR will be closed at #23.

**Pull request closed without merging**
