### PR TITLE
localization: Support Japanese display

### PR DESCRIPTION
**Pull request by muramura**
This PR, #21, is now in Japanese only.
---
name: Bug report
about: Create a report to help us improve

---

**Describe the bug**
A clear and concise description of the bug.

The location of the text is inconsistent.
The number of sentences is different.

**To Reproduce**

Perform lupdate on QT.

**Expected behavior**

If the customer's language is Japanese, it will be displayed in English.

**Log Files and Screenshots**
*Always* add screenshots and the QGC console log.

None

**Drone (please complete the following information):**
- Describe the type of drone.
- Photo of the IMU / autopilot setup if possible.

**Additional context**

### CODE REVIEW

**Comment by amilcarlucas** [comment]
This has now been merged, is there a way to download this version? Or do I need to compile the source?
In other words, is there a build server?

**Comment by meee1** [comment]
it will be here
https://github.com/CubePilot/qgroundcontrol-herelink/actions/runs/1430391344

**Comment by amilcarlucas** [comment]
Thanks Michael,

~~should I use the 32bit or the 64bit version?~~
Nevermind, just saw that 32bit is armv7 and 64bit is amd64.

**Comment by meee1** [comment]
we ship with 64
64 = aarch64

**Comment by amilcarlucas** [comment]
copyed the 32bit apk to a micro-SDcard
allowed installation of untrusted app sources
clicked on the apk to install it.
got the message: "App not installed. The package appears to be corrupt"

:(

**Comment by amilcarlucas** [comment]
The 64bit apk gives me the same result :(

**Comment by meee1** [comment]
agh i think i see the issue, they are not signed, as we dont release our signing key.

if you built it yourself however and signed it, it would work. (might need to change the app name as to not conflict)

in the mean time ill look at getting this into a beta image

**Comment by amilcarlucas** [comment]
Thank you, we have a japanese customer who needs this.

**Comment by meee1** [comment]
if its a herelink thats in japan, to pass MIC it need to originate from randy, there are specific settings around this to get certification

**Comment by amilcarlucas** [comment]
Yeap, I bought it indirectly from Randy, it has the japanese certification Sticker.

**Comment by meee1** [comment]
sweet, ill discuss with randy about pushing it directly to the japan release channel

**Comment by amilcarlucas** [comment]
That will be great!!

**Comment by amilcarlucas** [comment]
ArduCopter 4.1.2 support is a bit lagging in QGroundcontrol 4.0.8. It pop up an error right after connecting, and some settings are outdated.
Any plans to rebase the herelink fork on top of the upstream QGroundcontrol master?

**Pull request merged**
